export const metadata = {
  title: 'Create Next Apsssp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="ddd">{children}</body>
    </html>
  )
}
